"""Human-readable views of a degree catalog.

Turns a validated `Program` into display structures: what each requirement block
asks for, in English, and which courses could satisfy it.

Scope boundary — read this before adding to it:

* This module describes REQUIREMENTS. It knows nothing about any student.
* It never decides whether a requirement is *met*. That is the audit engine's job
  (`app/audit/`), which assigns a student's completed courses to blocks by solving
  an assignment problem.
* `prerequisite_tree` below expands prerequisites for DISPLAY only. Real graph
  analysis — critical path, topological ordering, eligibility — belongs in
  `app/audit/prereq_graph.py`. Do not grow this into a second implementation.

Like everything under `app/catalog/`, this must not import the LLM layer.
"""

from __future__ import annotations

from decimal import Decimal

from pydantic import BaseModel, Field

from app.catalog.schema import (
    AllOfBlock,
    Course,
    CreditsFromBlock,
    EachOfBlock,
    GpaBlock,
    NOfBlock,
    Program,
    RequirementBlock,
    ResidencyBlock,
)
from app.schemas.provenance import Provenance


class CourseSummary(BaseModel):
    code: str
    title: str
    credits: Decimal
    prerequisites: list[str] = Field(default_factory=list)
    terms_offered: list[str] = Field(default_factory=list)

    @classmethod
    def of(cls, course: Course) -> CourseSummary:
        return cls(
            code=course.code,
            title=course.title,
            credits=course.credits,
            prerequisites=list(course.prerequisites),
            terms_offered=[t.value for t in course.terms_offered],
        )


class BlockSummary(BaseModel):
    """One requirement block, described for a human reader."""

    block_id: str
    name: str
    kind: str
    #: Plain-English statement of what the block asks for, e.g. "Any 2 of: ...".
    requirement: str
    min_grade: str | None = None
    credits_required: Decimal | None = None
    courses_required: int | None = None
    eligible_courses: list[CourseSummary] = Field(default_factory=list)
    note: str | None = None
    advisor_approval_required: bool = False


class ProgramSummary(BaseModel):
    program_id: str
    program: str
    institution: str
    catalog_year: str
    total_credits_required: Decimal
    min_gpa: Decimal
    min_major_gpa: Decimal
    blocks: list[BlockSummary]

    #: Always VERIFIED: this is catalog data, read from a git-tracked file.
    #: Nothing here was generated by a language model.
    provenance: Provenance = Provenance.VERIFIED

    @property
    def course_requirement_credits(self) -> Decimal:
        """Credits explicitly demanded by blocks.

        Usually LESS than `total_credits_required` — the remainder is free
        electives. A larger value means the catalog over-constrains the degree and
        is probably an encoding error worth investigating.
        """
        return sum(
            (b.credits_required for b in self.blocks if b.credits_required is not None),
            Decimal(0),
        )


def _course_list(codes: list[str]) -> str:
    return ", ".join(codes) if codes else "(none)"


def describe_requirement(program: Program, block: RequirementBlock) -> str:
    """One sentence stating what `block` asks for."""
    match block:
        case AllOfBlock():
            return f"All of: {_course_list(block.courses)}"
        case NOfBlock():
            return f"Any {block.n} of: {_course_list(block.courses)}"
        case EachOfBlock():
            names = block.group_names or [f"Group {i + 1}" for i in range(len(block.groups))]
            parts = [
                f"{name} ({' or '.join(group)})"
                for name, group in zip(names, block.groups, strict=True)
            ]
            return "One course from each of: " + "; ".join(parts)
        case CreditsFromBlock():
            if block.course_filter is not None:
                filt = block.course_filter
                subjects = filt.subjects or ([filt.subject] if filt.subject else [])
                where = " or ".join(subjects) if subjects else "any subject"
                bounds = ""
                if filt.number_min is not None and filt.number_max is not None:
                    bounds = f" numbered {filt.number_min}-{filt.number_max}"
                elif filt.number_min is not None:
                    bounds = f" numbered {filt.number_min} or above"
                elif filt.number_max is not None:
                    bounds = f" numbered {filt.number_max} or below"
                excluded = f", excluding {_course_list(filt.exclude)}" if filt.exclude else ""
                return f"{block.credits_required} credits from {where}{bounds}{excluded}"
            return f"{block.credits_required} credits from: {_course_list(block.courses)}"
        case GpaBlock():
            return f"{block.scope.capitalize()} GPA of at least {block.min_gpa}"
        case ResidencyBlock():
            return (
                f"At least {block.min_credits_at_institution} credits "
                f"completed at {program.institution}"
            )
    raise ValueError(f"unhandled block type: {block.type!r}")  # pragma: no cover


def describe_block(program: Program, block: RequirementBlock) -> BlockSummary:
    eligible = [CourseSummary.of(c) for c in program.courses_for_block(block)]

    courses_required: int | None = None
    if isinstance(block, AllOfBlock):
        courses_required = len(block.courses)
    elif isinstance(block, NOfBlock):
        courses_required = block.n
    elif isinstance(block, EachOfBlock):
        courses_required = len(block.groups)

    return BlockSummary(
        block_id=block.id,
        name=block.name,
        kind=block.type,
        requirement=describe_requirement(program, block),
        min_grade=getattr(block, "min_grade", None),
        credits_required=getattr(block, "credits_required", None),
        courses_required=courses_required,
        eligible_courses=eligible,
        note=block.note,
        advisor_approval_required=block.advisor_approval_required,
    )


def describe_program(program: Program) -> ProgramSummary:
    return ProgramSummary(
        program_id=program.program_id,
        program=program.program,
        institution=program.institution,
        catalog_year=program.catalog_year,
        total_credits_required=program.total_credits_required,
        min_gpa=program.min_gpa,
        min_major_gpa=program.min_major_gpa,
        blocks=[describe_block(program, b) for b in program.requirement_blocks],
    )


def prerequisite_tree(program: Program, code: str, _seen: frozenset[str] | None = None) -> dict:
    """Expand a course's prerequisites for DISPLAY.

    Returns a nested dict: ``{"code", "title", "prerequisites": [...]}``.

    Cycles are truncated rather than raising, so a malformed catalog still renders
    something a human can read and debug. A real cycle *check* belongs in the audit
    engine's DAG, not here.
    """
    seen = _seen or frozenset()
    course = program.course(code)
    if course is None:
        return {"code": code, "title": "(unknown course)", "prerequisites": []}
    if code in seen:
        return {"code": code, "title": course.title, "prerequisites": [], "cycle": True}

    nested = seen | {code}
    direct = list(course.prerequisites)
    for group in course.prerequisite_groups:
        direct.extend(group)

    return {
        "code": course.code,
        "title": course.title,
        "credits": course.credits,
        "prerequisites": [prerequisite_tree(program, p, nested) for p in dict.fromkeys(direct)],
    }


def prerequisite_depth(program: Program, code: str) -> int:
    """How many courses deep the longest prerequisite chain runs, `code` included.

    A standalone course is depth 1. Display-only: the audit engine computes the
    real critical path across all *remaining* requirements, which is a different
    and harder question.
    """

    def walk(node: dict) -> int:
        kids = node.get("prerequisites") or []
        return 1 + max((walk(k) for k in kids), default=0)

    return walk(prerequisite_tree(program, code))
